version: '3.8'

services:

  laravel:
    build: ./backend
    volumes:
      - ./backend:/var/www
    environment:
      - DB_CONNECTION=mongodb
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_DATABASE=tfg
      - DB_USERNAME=root
      - DB_PASSWORD=marcpass
    ports:
      - "8000:8000"
    depends_on:
      - minio
      - mongodb
    networks:
      - app-network
    command: php artisan serve --host=0.0.0.0

  vue:
    build: ./frontend
    volumes:
      - ./frontend:/app
    depends_on:
      - laravel
    ports:
      - "8080:8080"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - vue
      - laravel
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=marcpass
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  minio:
    container_name: minioStorage
    image: minio/minio
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "minio123"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - app-network
    command: server /data --console-address ":9001"

volumes:
  mongodb_data:
  minio_data:

networks:
  app-network:
   driver: bridge
